version: "3.9"

networks:
  default:
    name: contest

volumes:
  mariadb_data:
    driver: local

configs:
  nginx_vhost:
    file: var/docker/nginx/nginx.conf
  php_ini:
    file: var/docker/php/php.ini-development
  dot_env:
    file: .env

services:

  mariadb:
    hostname: mariadb
    container_name: mariadb
    build:
      context: var/docker/mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - default

  php:
    hostname: php
    container_name: php
    build:
      context: var/docker/php
    depends_on:
      - mariadb
    volumes:
      - ./lib:/var/www/html/lib
      - ./public:/var/www/html/public
      - ./var/log:/var/www/html/var/log
    networks:
      - default
    configs:
      - source: php_ini
        target: usr/local/etc/php/php.ini
        mode: 0644
      - source: dot_env
        target: var/www/html/.env
        mode: 0644
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    hostname: nginx
    container_name: nginx
    build:
      context: var/docker/nginx
    depends_on:
      - php
    volumes:
      - ./lib:/var/www/html/lib
      - ./public:/var/www/html/public
      - ./var/log:/var/www/html/var/log
    networks:
      - default
    configs:
      - source: nginx_vhost
        target: etc/nginx/conf.d/default.conf
        mode: 0644
    ports:
      - "80:80"